server:
  port: ${prot:8080}

spring:
  codec:
    max-in-memory-size: 500KB
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb    #jdbc:h2:mem:sys
    #username: sa # username? password? ??? ??? ??
    #password:
    #generate-unique-name: false
    driver-class-name: org.h2.Driver
    generate-unique-name: false
  jpa:
    hibernate:
      ddl-auto: create # ??????? ??? ? ??????? ????? ?? ??? ??
    properties:
      hibernate:
        format_sql: true # ???? query? ???
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      encoding: UTF-8


logging.level:
  org.hibernate.SQL: debug
  org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG


